### ISSUE TITLE
Are These Bugs?

### ISSUE THREAD

**Issue by anliting** [anliting/theta#1]
Are these bugs?:
https://github.com/anliting/theta/blob/master/src/Server/WebServer/static/index/Header.js#L6
https://github.com/anliting/theta/blob/master/src/Server/WebServer/static/index/Login.js#L11
https://github.com/anliting/theta/blob/master/src/Server/WebServer/static/index/Register.js#L11

Consider this:
```
function f(){
    f=0
}
f()
f() // throws
```

**Comment by b04902012** [comment]
Have been solved. Please check.

**Comment by anliting** [comment]
Checked; thanks, closing.
